---
jwtSigningKey: "test"
authenticationMethod: "builtin"
publicUrl: "https://gnt-cc.example.com"
users:
  - username: "admin"
    password: "test"
clusters:
  - name: "test"
    hostname: "test-cluster.example.com"
    port: 5080
    description: "Ganeti Test Cluster"
    username: "test"
    password: "supersecret"
    ssl: True