before:
  hooks:
    - cp ../README.md ./README.md
    - cp ../LICENSE ./LICENSE
    - go get -u github.com/swaggo/swag/cmd/swag
    - go get -u github.com/GeertJohan/go.rice/rice
    - go mod download
    - swag init
    - rice embed-go

builds:
  - goos:
      - linux
    goarch:
      - amd64

archives:
  - files:
      - config.example.yaml
      - README.md
      - LICENSE

checksum:
  algorithm: sha512

release:
  github:
    owner: sipgate
    name: gnt-cc
  draft: true
  prerelease: auto

changelog:
  sort: asc
