---
bind: 127.0.0.1
port: 8000
developmentMode: true
logLevel: warning
jwtSigningKey: "weNFEWFWKJEnfWknfewlkjenfFE"
jwtExpire: "2000m"
authenticationMethod: "builtin"
publicUrl: "https://gnt-cc.example.com"
users:
  - username: "admin"
    password: "admin"
  - username: "admin2"
    password: "admin"
ldapConfig:
  host: "some.server"
  port: 389
  skipCertificateVerify: false
  userFilter: "(&(objectClass=posixAccount)(uid=%s))"
  groupFilter: "(&(objectClass=posixGroup)(cn=someGroupName)(memberUid=%s))"
  baseDn: "dc=domain,dc=org"
rapiConfig:
  skipCertificateVerify: false
clusters:
  - name: "test-cluster"
    hostname: "test-cluster.example.com"
    port: 5080
    description: "Ganeti Test Cluster"
    username: "gnt-cc"
    password: "gnt-cc"
    ssl: true
  - name: "production-cluster"
    hostname: "prod-cluster.example.com"
    port: 5080
    description: "Ganeti Production Cluster"
    username: "gnt-cc"
    password: "somepassword"
    ssl: true